version: "3.7"

services:

  nginx:
    container_name: todos
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - "./build:/usr/share/nginx/html"
    ports:
      - "8000:8000"
