version: "3.7"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todos
      PGDATA: ./data/db
  db_test:
    image: postgres
    volumes:
      - ./data/db_test:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todos
      PGDATA: ./data/db_test
  api:
    build: ./
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./:/app/
      - ./data/media:/media/
      - ./data/media/test:/media/test/
    ports:
      - 8002:8000
    environment:
      - ALLOWED_ORIGINS=http://127.0.0.1:8000
      - DATABASE_URI=postgresql+psycopg2://postgres:postgres@db:5432/todos
      - SECRET_KEY=09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - ADMIN_PASSWORD=welcome
      - MEDIA_ROOT=/media/
    depends_on:
      - db
      - db_test
  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./nginx_config.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api